import React, { useState } from 'react'
import Select from 'react-dropdown-select';
import { MdVisibility } from 'react-icons/md';


const Drop = () => {



    const options = [
        { value: '', label: 0 },
        { value: 'Afghanistan', label: 1, },
        { value: 'Aland Islands', label: 2, },
        { value: 'Afghanistan', label: 3, },
        { value: ' Aland Islands', label: 4, },
        { value: ' Albania', label: 5, },
        { value: ' Algeria', label: 6, },
        { value: 'American Samoa', label: 7, },
        { value: 'Andorra', label: 8, },
        { value: 'Angola', label: 9, },
        { value: 'Anguilla', label: 10, },
        { value: 'Antigua And Barbuda', label: 11, },
        { value: 'Argentina, Armenia', label: 12, },
        { value: 'Aruba', label: 13, },
        { value: 'Australia', label: 14, },
        { value: 'Austria', label: 15, },
        { value: 'Azerbaijan', label: 16, },
        { value: 'Bahrain', label: 17, },
        { value: 'Bangladesh', label: 18, },
        { value: 'Barbados', label: 19, },
        { value: 'Belarus', label: 20, },
        { value: ' Belgium', label: 21, },
        { value: 'Belize', label: 22, },
        { value: 'Benin', label: 23, },
        { value: 'Bermuda', label: 24, },
        { value: 'Bhutan', label: 25, },
        { value: 'Bolivia', label: 26, },
        { value: 'Bonaire', label: 27, },
        { value: 'Bosnia And Herzegovina', label: 28, },
        { value: 'Botswana', label: 29, },
        { value: 'Bouvet Island', label: 30, },
        { value: 'Brazil', label: 31, },
        { value: 'British Indian Ocean Territory', label: 32, },
        { value: 'British Virgin Islands', label: 33, },
        { value: 'Brunei', label: 34, },
        { value: 'Bulgaria', label: 35, },
        { value: 'Burkina Faso', label: 36, },
        { value: 'Burundi', label: 37, },
        { value: 'Cambodia', label: 38, },
        { value: 'Cameroon', label: 39, },
        { value: 'Canada', label: 40, },
        { value: 'Cape Verde', label: 41, },
        { value: 'Caribbean Netherlands', label: 42, },
        { value: 'Cayman Islands', label: 43, },
        { value: 'Central African Republic', label: 44, },
        { value: 'Chad', label: 45, },
        { value: 'Chile', label: 46, },
        { value: 'China', label: 47, },
        { value: 'Christmas Island', label: 48, },
        { value: 'Cocos (Keeling) Islands', label: 49, },
        { value: 'Colombia, Comoros', label: 50, },
        { value: 'Cook Islands', label: 51, },
        { value: 'Costa Rica', label: 52, },
        { value: 'Croatia', label: 53, },
        { value: 'Cuba', label: 54, },
        { value: 'Curacao', label: 55, },
        { value: 'Cyprus', label: 56, },
        { value: 'Czech Republic', label: 57, },
        { value: 'Democratic Republic Of The Congo', label: 58, },
        { value: 'Denmark', label: 59, },
        { value: 'Djibouti', label: 60, },
        { value: 'Dominica', label: 61, },
        { value: 'Dominican Republic', label: 62, },
        { value: 'Ecuador', label: 63, },
        { value: 'Egypt', label: 64, },
        { value: 'El Salvador', label: 65, },
        { value: 'England', label: 66, },
        { value: 'Equatorial Guinea', label: 67, },
        { value: 'Eritrea', label: 68, },
        { value: 'Estonia', label: 69, },
        { value: 'Ethiopia', label: 70, },
        { value: 'Falkland Islands', label: 71, },
        { value: 'Faroe Islands', label: 72, },
        { value: 'Fiji', label: 73, },
        { value: 'Finland', label: 74, },
        { value: 'France', label: 75, },
        { value: 'French Guiana', label: 76, },
        { value: 'French Polynesia', label: 77, },
        { value: 'Gabon', label: 78, },
        { value: 'Gambia', label: 79, },
        { value: 'Georgia', label: 80, },
        { value: 'Germany', label: 81, },
        { value: 'Ghana', label: 82, },
        { value: 'Gibraltar', label: 83, },
        { value: 'Greece', label: 84, },
        { value: ' Greenland', label: 85, },
        { value: 'Grenada', label: 86, },
        { value: 'Guadeloupe', label: 87, },
        { value: 'Guam', label: 88, },
        { value: 'Guatemala', label: 89, },
        { value: 'Guernsey', label: 90, },
        { value: 'Guinea', label: 91, },
        { value: 'Guinea-Bissau', label: 92, },
        { value: 'Guyana', label: 93, },
        { value: 'Haiti', label: 94, },
        { value: 'Honduras', label: 95, },
        { value: 'Hong Kong', label: 96, },
        { value: 'Hungary', label: 97, },
        { value: 'Iceland', label: 98, },
        { value: 'India', label: 99, },
        { value: 'Indonesia', label: 100 },
        { value: 'Iran', label: 101 },
        { value: 'Iraq', label: 102 },
        { value: 'Ireland', label: 103 },
        { value: 'Isle Of Man', label: 104 },
        { value: 'Israel', label: 105 },
        { value: 'Italy', label: 106 },
        { value: 'Ivory Coast', label: 107 },
        { value: 'Jamaica', label: 108 },
        { value: 'Japan', label: 109 },
        { value: 'Jersey', label: 110 },
        { value: 'Jordan', label: 111 },
        { value: 'Kazakhstan', label: 112 },
        { value: 'Kenya', label: 113 },
        { value: 'Kiribati', label: 114 },
        { value: 'Kosovo', label: 115 },
        { value: 'Kuwait', label: 116 },
        { value: 'Kyrgyzstan', label: 117 },
        { value: 'Laos', label: 118 },
        { value: 'Latvia', label: 119 },
        { value: 'Lebanon', label: 120 },
        { value: 'Lesotho', label: 121 },
        { value: 'Liberia', label: 122 },
        { value: 'Libya', label: 123 },
        { value: 'Liechtenstein', label: 124 },
        { value: 'Lithuania', label: 125 },
        { value: 'Luxembourg', label: 126 },
        { value: 'Macau', label: 127 },
        { value: 'Macedonia', label: 128 },
        { value: 'Madagascar', label: 129 },
        { value: 'Malawi', label: 130 },
        { value: 'Malaysia', label: 131 },
        { value: 'Maldives', label: 132 },
        { value: 'Mali', label: 133 },
        { value: 'Malta', label: 134 },
        { value: 'Marshall Islands', label: 135 },
        { value: 'Martinique', label: 136 },
        { value: 'Mauritania', label: 137 },
        { value: 'Mauritius', label: 138 },
        { value: 'Mayotte', label: 139 },
        { value: 'Mexico', label: 140 },
        { value: 'Micronesia', label: 141 },
        { value: 'Moldova', label: 142 },
        { value: 'Monaco', label: 143 },
        { value: 'Mongolia', label: 144 },
        { value: 'Montenegro', label: 145 },
        { value: 'Montserrat', label: 146 },
        { value: 'Morocco', label: 147 },
        { value: 'Mozambique', label: 148 },
        { value: 'Myanmar (Burma)', label: 149 },
        { value: 'Nagorno-Karabakh', label: 150 },
        { value: 'Namibia', label: 151 },
        { value: 'Nauru', label: 152 },
        { value: 'Nepal', label: 153 },
        { value: 'Netherlands', label: 154 },
        { value: 'Netherlands Antilles', label: 155 },
        { value: 'New Caledonia', label: 156 },
        { value: 'New Zealand', label: 157 },
        { value: 'Nicaragua', label: 158 },
        { value: 'Niger', label: 159 },
        { value: 'Nigeria', label: 160 },
        { value: 'Niue', label: 161 },
        { value: 'Norfolk Island', label: 162 },
        { value: 'North Korea', label: 163 },
        { value: 'Northern Mariana Islands', label: 164 },
        { value: ' Norway', label: 165 },
        { value: 'Oman', label: 166 },
        { value: 'Pakistan', label: 167 },
        { value: 'Palau', label: 168 },
        { value: 'Palestine', label: 169 },
        { value: 'Panama', label: 170 },
        { value: 'Papua New Guinea', label: 171 },
        { value: 'Paraguay', label: 172 },
        { value: 'Peru', label: 173 },
        { value: 'Philippines', label: 174 },
        { value: 'Pitcairn Islands', label: 175 },
        { value: 'Poland', label: 176 },
        { value: 'Portugal', label: 177 },
        { value: 'Puerto Rico', label: 178 },
        { value: 'Qatar', label: 179 },
        { value: 'Republic Of The Congo', label: 180 },
        { value: 'Reunion', label: 181 },
        { value: 'Romania', label: 182 },
        { value: 'Russia', label: 183 },
        { value: 'Rwanda', label: 184 },
        { value: 'Saint Barthelemy', label: 185 },
        { value: 'Saint Helena', label: 186 },
        { value: 'Saint Kitts And Nevis', label: 187 },
        { value: 'Saint Lucia', label: 188 },
        { value: 'Saint Martin', label: 189 },
        { value: 'Saint Pierre And Miquelon', label: 190 },
        { value: 'Saint Vincent And The Grenadines', label: 191 },
        { value: 'Samoa', label: 192 },
        { value: 'San Marino', label: 193 },
        { value: 'Sao Tome And Principe', label: 194 },
        { value: 'Saudi Arabia', label: 195 },
        { value: 'Scotland', label: 196 },
        { value: 'Senegal', label: 197 },
        { value: 'Serbia', label: 198 },
        { value: 'Serbia And Montenegro', label: 199 },
        { value: 'Seychelles', label: 200 },
        { value: 'Sierra Leone', label: 201 },
        { value: 'Singapore', label: 202 },
        { value: 'Sint Maarten', label: 203 },
        { value: 'Slovakia', label: 204 },
        { value: 'Slovenia', label: 205 },
        { value: 'Solomon Islands', label: 206 },
        { value: 'Somalia', label: 207 },
        { value: 'South Africa', label: 208 },
        { value: 'South Georgia And The South Sandwich Islands', label: 209 },
        { value: 'South Korea', label: 210 },
        { value: 'South Sudan', label: 211 },
        { value: 'Spain', label: 212 },
        { value: 'Sri Lanka', label: 213 },
        { value: 'Sudan', label: 214 },
        { value: 'Suriname', label: 215 },
        { value: 'Svalbard And Jan Mayen', label: 216 },
        { value: 'Swaziland', label: 217 },
        { value: 'Sweden', label: 218 },
        { value: 'Switzerland', label: 219 },
        { value: 'Syria', label: 220 },
        { value: 'Taiwan', label: 221 },
        { value: 'Tajikistan', label: 222 },
        { value: 'Tanzania', label: 223 },
        { value: 'Thailand', label: 224 },
        { value: 'The Bahamas', label: 225 },
        { value: 'Timor-Leste', label: 226 },
        { value: 'Togo', label: 227 },
        { value: 'Tokelau', label: 228 },
        { value: 'Tonga', label: 229 },
        { value: 'Transnistria', label: 230 },
        { value: 'Trinlabelad And Tobago', label: 231 },
        { value: 'Tunisia', label: 232 },
        { value: 'Turkey', label: 233 },
        { value: 'Turkmenistan', label: 234 },
        { value: 'Turks And Caicos Islands', label: 235 },
        { value: 'Tuvalu', label: 236 },
        { value: 'Uganda', label: 237 },
        { value: 'Ukraine', label: 238 },
        { value: 'United Arab Emirates', label: 239 },
        { value: 'United Kingdom', label: 240 },
        { value: 'United States Of America', label: 241 },
        { value: 'Uruguay', label: 242 },
        { value: 'US Virgin Islands', label: 243 },
        { value: 'Uzbekistan', label: 244 },
        { value: 'Vanuatu', label: 245 },
        { value: 'Vatican City', label: 246 },
        { value: 'Venezuela', label: 247 },
        { value: 'Vietnam', label: 248 },
        { value: 'Wales', label: 249 },
        { value: 'Wallis And Futuna', label: 250 },
        { value: 'Western Sahara', label: 251 },
        { value: 'Yemen', label: 252 },
        { value: 'Zambia', label: 253 },
        { value: 'Zimbabwe', label: 254 }
    ];


    return (
        <>
            <div className='reasonbox' >
                <Select
                    options={options}
                    labelField="value"
                    valueField="label"
                    dropdownHeight={'150px'}
                    placeholder="select"
                    dropdownGap={10}
                    className='select'
                />
            </div>
        </>
    )
}

export default Drop
